#!/bin/sh

rm -rf /app/bedrock/web/wp
rm -rf /app/bedrock/vendor
rm -rf /app/bedrock/web/app/themes/sage/node_modules
rm -rf /app/bedrock/web/app/themes/sage/public/*
rm -rf /app/bedrock/web/app/themes/sage/vendor
rm -rf /app/sage/node_modules
rm -rf /app/sage/vendor
rm -rf /app/sage/public
